version: '2'
services:
    mysql:
        extends:
            file: docker-compose/mysql.yaml
            service: mysql
        networks:
            - database
    spring-rest:
        extends:
            file: docker-compose/services.yaml
            service: spring-rest
        networks:
            - database
        links:
            - mysql
networks:
    database:
volumes:
    mysql-data:
